theme = "everforest_light"

[editor]
scroll-lines = 1

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["keep_primary_selection", "collapse_selection"]

[keys.normal.space]
c = ":buffer-close"
q = ":quit-all"
w = ":write-all"
