theme = "everforest_light"

[editor]
scroll-lines = 1
scrolloff = 100

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["keep_primary_selection", "collapse_selection"]
up = [
  "move_visual_line_up",
  "move_visual_line_up",
  "move_visual_line_up",
  "move_visual_line_up",
  "move_visual_line_up",
]
down = [
  "move_visual_line_down",
  "move_visual_line_down",
  "move_visual_line_down",
  "move_visual_line_down",
  "move_visual_line_down",
]
left = "goto_line_start"
right = "goto_line_end"

[keys.normal.space]
q = ":quit-all"
w = ":write-all"
x = ":buffer-close"
z = ":reflow"

[keys.select]
up = [
  "extend_visual_line_up",
  "extend_visual_line_up",
  "extend_visual_line_up",
  "extend_visual_line_up",
  "extend_visual_line_up",
]
down = [
  "extend_visual_line_down",
  "extend_visual_line_down",
  "extend_visual_line_down",
  "extend_visual_line_down",
  "extend_visual_line_down",
]
left = "extend_to_line_start"
right = "extend_to_line_end"

[keys.select.space]
q = ":quit-all"
w = ":write-all"
x = ":buffer-close"
z = ":reflow"
